server:
  port: 8808
spring:
  redis:
    expire: 600000
    database: 6 # Redis使用的库
    host: 10.12.9.189
    port: 6379 #端口号
    password:   #redis密码
    #    lettuce:
    #      pool:
    #        max-active: 8     # 连接池最大连接数（使用负值表示没有限制）
    #        max-wait: 10000   # 连接池最大阻塞等待时间（使用负值表示没有限制）
    #        max-idle: 8       # 连接池中的最大空闲连接
    #        min-idle: 1       # 连接池中的最小空闲连接
    timeout: 10000        #  连接超时时间（毫秒）
    cache:
      type: redis
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
  jpa:
    database: oracle
  datasource:
      driver-class-name: oracle.jdbc.OracleDriver
      username: xinjianxun
      password: 751004
      url: jdbc:oracle:thin:@10.187.10.209:20209:pjil

mybatis-plus:
   configuration:
     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: com.cpic
  #30分钟过期
  expiration: 1800000
#checkTokenFilter  里使用
cpic:
  loginUrl: /api/user/login
